optimizer:
  type: AdamW
  kwargs:
    lr: 5e-4
    weight_decay: 0.05

scheduler:
  type: CosLR
  kwargs:
    epochs: 150
    initial_epochs: 10


dataset:
  train:
    _base_: cfgs/dataset_configs/ModelNet40FewShot.yaml
    others:
      subset: train
  val:
    _base_: cfgs/dataset_configs/ModelNet40FewShot.yaml
    others:
      subset: test
  test:
    _base_: cfgs/dataset_configs/ModelNet40.yaml
    others:
      subset: test

model:
  NAME: PointTransformer
  embed_dim: 384
  depth: 12
  drop_path_rate: 0.3
  cls_dim: 40
  num_heads: 6
  group_size: 64
  num_group: 32
  prompt_group_size: 64
  prompt_num_group: 32
  type: pos


npoints: 1024
total_bs: 4
step_per_update: 1
max_epoch: 150
grad_norm_clip: 10
